-- These tables need to be created in a PostgreSQL database for the app
create table users (id UUID PRIMARY KEY, username TEXT, password TEXT);
create table posts (id UUID PRIMARY KEY, username TEXT, title TEXT, preview TEXT, content text, created TIMESTAMPTZ NOT NULL DEFAULT NOW());
create table comments (id UUID PRIMARY KEY, post_id TEXT, author TEXT, content TEXT, created TIMESTAMPTZ NOT NULL DEFAULT NOW());